version: '3.8'                                      # docker-compose 파일 버전

services:                                           # 서비스들 선언
  mysql:                                            # 서비스명 선언
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:                                        # {호스트}:{컨테이너}
      - .db/conf.d:/etc/mysql/conf.d                # MySQL 설정 파일
      - .db/initdb.d:/docker-entrypoint-initdb.d    # sh, sql을 파일명 알파벳순으로 수행. 테이블 create, insert 쿼리 파일이 있음
    ports:
      - "3306:3306"                                 # 외부로 노출시킬 port
    environment:                                    # 환경 변수
      - MYSQL_DATABASE=ballet_local
      - MYSQL_USER=ballet_local_user
      - MYSQL_PASSWORD=balletlocal123
      - MYSQL_ROOT_PASSWORD=balletlocal123
      - TZ=Asia/Seoul
