spring:
  datasource:
    url: jdbc:h2:mem:mydb
    usernmae: ballet-local
    password: ballelocal
    driver-class-name: org.h2.driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect