server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allonge
    username: app_user
    password: balletlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20 #hikari DBCP는 tomcat DBCP와 다르게 사용하지 않는 커넥션을 회수한다.
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: always # Batch에 사용되는 SQL 초기화 스크립트를 실행
                                # embedded : 내장형 데이터베이스를 사용할 때만 메타데이터 테이블을 생성하는 옵션
                                # never : 생성하지 않는 옵션
  logging:
    level:
      com.ballet.allonge: debug
      org.springframework.web.servelt: debug
      org.hibernate.type.descripter.sql.BasicBinder: trace # 파라미터를 확인할 수 있는 옵션
